### ISSUE TITLE
Sonic Boom (sonicbom) - orientation flipped

### ISSUE THREAD

**Issue by arnoldsecret** [barry65536/FBAlpha#6] opened 2018-12-15 13:44 UTC
![sonicbom-181215-214209](https://user-images.githubusercontent.com/41223243/50043612-81995880-00b2-11e9-88ff-79f941b54f66.png)
required an override on Libretro for the correct orientation.

**Comment by barry65536** [comment] 2018-12-15 17:07
The libretro port needs to support the BDF_ORIENTATION_FLIPPED flag. This needs to be reported to the libretro core.

**Comment by barbudreadmon** [comment] 2018-12-16 07:53
> The libretro port needs to support the BDF_ORIENTATION_FLIPPED flag. This needs to be reported to the libretro core.

We already do that though, i'll investigate

**Comment by barbudreadmon** [comment] 2018-12-16 09:00
@barry65536 I think the issue is unrelated to the port, the game is actually missing `BDF_ORIENTATION_FLIPPED` in its codebase : 
https://github.com/barry65536/FBAlpha/blob/6716b6786e2e9cc5852e3eb37b2797da57c2dc26/src/burn/drv/sega/d_sys16b.cpp#L9820-L9837

Are you sure it is working properly in standalone ?

**Comment by dinkc64** [comment] 2018-12-16 13:48
sonicbom was upsidedown for me when I tried it.  I remember it working just fine several months ago.
I killed off the game's nvram and rebooted the game, and now its rotated properly.  I can only guess that something had changed with the format of the game's nvram, perhaps?  ... or something? :)

**Comment by barbudreadmon** [comment] 2018-12-16 13:55
Without my commit, i'm still getting the issue with fresh nvram and dips to default.

**Comment by dinkc64** [comment] 2018-12-16 14:13
getting weirdness on my 32bit-side too - it's just a fluke that it was upright for me after clearing the dips and nvram because I can't reproduce it again.

**Comment by dinkc64** [comment] 2018-12-17 04:10
The fix I made should solve the problem.  It does, of course, need testing. :)

**Comment by dinkc64** [comment] 2018-12-18 00:10
arnoldsecret, thanks again for the nice bug report. :)

best regards,
- dink

**Comment by dinkc64** [comment] 2018-12-19 23:50
Is everything OK with this one?

**Comment by barbudreadmon** [comment] 2018-12-20 07:16
Sorry, i wanted to beat the game to make sure everything was alright, but after dying like 20 times on the same screen, i withdrawed. Everything i saw looked fine so i think it's ok to close the issue.

**Comment by dinkc64** [comment] 2018-12-20 14:17
hahaha.  :)

**Closed by dinkc64** 2018-12-20 14:17 UTC
